name: Build Kernel X00TD 4.19
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Env
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libncurses5-dev binutils-aarch64-linux-gnu libelf-dev

      - name: Clone Toolchain (Proton Clang)
        run: git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Clone Kernel Source
        run: git clone --depth=1 https://github.com/SonicBSV/android_kernel_asus_sdm660-4.19.git -b Ratibor-Lineage source

      - name: Build Kernel
        run: |
          cd source
          export PATH=$(pwd)/../clang/bin:$PATH
          make O=out ARCH=arm64 X00TD_defconfig
          make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=clang \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                      AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip

      - name: Package ZIP
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git
          cp source/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/ || cp source/out/arch/arm64/boot/Image.gz AnyKernel3/
          cd AnyKernel3
          zip -r9 Kernel-X00TD-4.19.zip *

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-Kernel-SonicBSV
          path: AnyKernel3/Kernel-X00TD-4.19.zip
