name: Build Kernel X00TD Final
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04 # Menggunakan versi Ubuntu yang lebih stabil untuk kernel lama
    steps:
      - name: Setup Env
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libncurses5-dev binutils-aarch64-linux-gnu libelf-dev

      - name: Clone Toolchain (AOSP Clang)
        run: |
          # Mengunduh AOSP Clang yang lebih kompatibel
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang-aosp

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/SonicBSV/android_kernel_asus_sdm660-4.19 source

      - name: Build Kernel
        run: |
          cd source
          # Mengatur path ke compiler AOSP Clang
          export PATH=$(pwd)/../clang-aosp/clang-r383902/bin:$PATH
          
          # Cek defconfig
          if [ -f arch/arm64/configs/X00TD_defconfig ]; then
              CONF=X00TD_defconfig
          else
              CONF=sdm660_defconfig
          fi
          
          make O=out ARCH=arm64 $CONF
          make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=clang \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Package ZIP
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git
          find source/out/arch/arm64/boot/ -name "Image.gz*" -exec cp {} AnyKernel3/ \;
          cd AnyKernel3
          zip -r9 Kernel-X00TD-Final.zip *

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-X00TD-Result
          path: AnyKernel3/Kernel-X00TD-Final.zip
